SUBROUTINE RES(T,Y,YPRIME,DELTA,IRES,RPAR,IPAR)
    implicit none
    !DECLARAÇÃO DE VARIÁVEIS PARA A DASSL
    DOUBLE PRECISION T, Y(*), YPRIME(*), DELTA(*), RPAR(*)
    INTEGER IRES,IPAR(*)
    !DECLARAÇÃO DE VARIÁVEIS DO PROBLEMA
    DOUBLE PRECISION NL, NI, dNL, dNI, KTRANSCAL, TSIS, TFREEZ
    !RELITERANDO AS VARIÁVEIS DA DASSL 
    !N.A. (APENAS PARA FINS DIDÁTICOS. É RECOMENDÁVEL TRABALHAR DIRETAMENTE COM Y,YPRIME, IPAR E RPAR)
    NL=Y(1)
    dNL=YPRIME(1)
    NI=Y(2)
    dNI=YPRIME(2)
    !FOPRIME=YPRIME(2) !FOPRIME NÃO SERÁ UTILIZADO NAS EQUAÇÕES, ENTÃO PODE SER IGNORADO
    KTRANSCAL=RPAR(1)
    TSIS=RPAR(2)
    TFREEZ=RPAR(3) 
    !------------------------------------------
    !FORMULAÇÃO DO PROBLEMA
    !AQUI DEVEM SER INSERIDAS AS EQUAÇÕES DIFERENCIAIS E ALGÉBRICAS
    !ELAS DEVEM ESTAR NA FORMA DELTA(I)=F(Y,Y',t)
    !e.g. PARA UMA VARIÁVEL 'F' GENÉRICA TEMOS A EQUAÇÃO: dF/dt=F -> DELTA=dF/dt-F
    !     PARA A DASSL F=Y, LOGO, A EQUAÇÃO DEVE SER ESCRITA EM FORTRAN COMO: DELTA(I)=YPRIME(I)-Y(I) PARA I=1,...,NEQ
    DELTA(1)=(dNL)-(-1.*DNI) !EQUAÇÃO DIFERENCIAL
    if (NL>0 .AND. NI>0) THEN
      DELTA(2)=(dNL)-(KTRANSCAL*(TSIS-TFREEZ))  !EQUAÇÃO ALGÉBRICA
    else
      DELTA(2)=(dNL)-(0.)  !taxa nula se alguma fase se esgotar
    endif
    
END SUBROUTINE
